config/routes.rb
Rails.application.routes.draw do
  resources :items
  get '/menu' => 'menu#index'
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  enum kind: [ :food, :drink ]

  validates :title, presence: true
  validates :price, presence: true
  validates :kind, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item

  validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :price)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @drinks = Item.drink
    @food = Item.food
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @item = Item.find(params.fetch(:item))
    @order = Order.new item: @item
    @action_title = 'Order'
  end

  # GET /orders/1/edit
  def edit
    if @order.paid_at.present?
      # Already paid
      return redirect_to @order
    end

    @action_title = 'Pay'
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update paid_at: Time.now.utc
        format.html { redirect_to @order, notice: 'Order was successfully paid.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :title, class: 'col-12 col-sm-2 col-form-label' %>
    <div class="col-12 col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :price, class: 'col-12 col-sm-2 col-form-label' %>
    <div class="col-12 col-sm-10">
      <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<span class="item-title"><%= item.title %></span> · <span class="item-price"><%= number_to_currency item.price %></span>
<% if local_assigns.fetch(:show_order, false) %>
    · <%= link_to 'Order', new_order_path(item: item.id) %>
<% end %>

app/views/items/edit.html.erb
<h1 class="text-center mt-2">Editing Item</h1>

<%= render 'form', item: @item %>

<div class="btn-group">
    <%= link_to 'Show', @item, class: 'btn' %>
    <%= link_to 'Back', items_path, class: 'btn' %>
</div>

app/views/items/index.html.erb
<div id="notice"><%= notice %></div>

<h1 class="text-center mt-3 mb-2">Items</h1>

<section class="card-group">
  <% @items.each do |item| %>
    <div class="card text-center mb-3">
      <div class="card-block">
        <%= link_to item do %>
          <h4 class="card-title"><%= render item %></h4>
        <% end %>
      </div>
      <div class="card-footer">
        <div class="btn-group">
          <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-sm btn-outline-primary' %>
          <%= link_to 'Destroy', item, method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</section>

<div class="mt-2 mb-4 text-center">
  <div class="btn-group">
    <%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/items/new.html.erb
<h1 class="text-center mt-2">New Item</h1>

<%= render 'form', item: @item %>

<div class="btn-group">
    <%= link_to 'Back', items_path, class: 'btn' %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe on Rails</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container-fluid">
      <%= yield %>
    </main>
  </body>
</html>

app/views/menu/index.html.erb
<h1 class="text-center mt-2">Menu</h1>

<h2 class="text-center mt-3">Drinks</h2>
<ul class="nav flex-column text-center">
  <% @drinks.each do |item| %>
    <li class="nav-item"><%= render item, show_order: true %></li>
  <% end %>
</ul>

<h2 class="text-center mt-3">Food</h2>
<ul class="nav flex-column text-center">
  <% @food.each do |item| %>
    <li class="nav-item"><%= render item, show_order: true %></li>
  <% end %>
</ul>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render order.item %>

  <%= f.hidden_field :item_id %>

  <div class="actions">
    <%= f.submit @action_title %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> ·
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= render order.item %></td>
        <td>
          <% if order.paid_at.present? %>
            <%= time_tag order.paid_at, time_ago_in_words(order.paid_at) + ' ago' %>
          <% else %>
            <%= 'Unpaid' %>
          <% end %>
        </td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back to menu', menu_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= render @order.item %></h2>

<% if @order.paid_at.present? %>
<p>
  <strong>Paid:</strong>
  <%= time_tag @order.paid_at, time_ago_in_words(@order.paid_at) + ' ago' %>
</p>
<% else %>
<p>
  <strong>Unpaid:</strong>
  <%= link_to 'Pay now', edit_order_path(@order) %>
</p>
<% end %>

<%= link_to 'See menu', menu_path %> ·
<%= link_to 'All orders', orders_path %>